Update TestTypeone.yml

diff --git a/.github/workflows/TestTypeone.yml b/.github/workflows/TestTypeone.yml
--- a/.github/workflows/TestTypeone.yml
+++ b/.github/workflows/TestTypeone.yml
@@ -5,46 +5,46 @@ on: workflow_dispatch
 
 
 jobs:
- # post_api_call_perf:
- #   runs-on: ubuntu-latest
+ post_api_call_perf:
+   runs-on: ubuntu-latest
   
- #   steps:
- #    - name: Checkout Repository
- #      uses: actions/checkout@v2
- #    - name: post_api_call_perf
+   steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v2
+    - name: post_api_call_perf
 
- #      run: |
+      run: |
 
- #          apiUrl="https://venkata7.service-now.com/api/sn_devops/v1/devops/tool/test?toolId=7bae922dc375c250c95605bdc001314c&testType=Smoke"
+          apiUrl="https://venkata7.service-now.com/api/sn_devops/v1/devops/tool/test?toolId=7bae922dc375c250c95605bdc001314c&testType=Smoke"
           
- #          requestBody='{"toolId": "7bae922dc375c250c95605bdc001314c", "buildNumber": '${{ github.run_number }}' , "workflow": "Test API Call", "repository": "VenkataPrasad01/GithubActionsymls", "stageName":"post_api_call","pipelineName":"TestType1", "testType": "Smoke", "buildNumber": '${{ github.run_number }}', "buildId": '${{ github.run_id }}' , "attemptNumber" : '${{ github.run_attempt }}', "testSummaries": [{"name": "GitHub Test Summary - smoke","passedTests": 1,"failedTests": 1,"skippedTests": 1,"ignoredTests": 0,"blockedTests": 1,"totalTests": 4,"startTime": "2023-12-14T23:31:31z","endTime": "2023-12-14T23:31:31z","duration": 0.0,"testType": "Smoke", "suites": []}] }'
+          requestBody='{"toolId": "7bae922dc375c250c95605bdc001314c", "buildNumber": '${{ github.run_number }}' , "workflow": "TestType1", "repository": "VenkataPrasad01/GithubActionsymls", "stageName":"post_api_call","pipelineName":"VenkataPrasad01/GithubActionsymls/TestType1", "testType": "Smoke", "buildNumber": '${{ github.run_number }}', "buildId": '${{ github.run_id }}' , "attemptNumber" : '${{ github.run_attempt }}', "testSummaries": [{"name": "GitHub Test Summary - smoke","passedTests": 1,"failedTests": 1,"skippedTests": 1,"ignoredTests": 0,"blockedTests": 1,"totalTests": 4,"startTime": "2023-12-14T23:31:31z","endTime": "2023-12-14T23:31:31z","duration": 0.0,"testType": "Smoke", "suites": []}] }'
 
- #          auth="ZGV2b3BzLmludGVncmF0aW9uLnVzZXI6VGVzdGluZzEh"
+          auth="ZGV2b3BzLmludGVncmF0aW9uLnVzZXI6VGVzdGluZzEh"
 
- #          authHeader="Basic $auth"
+          authHeader="Basic $auth"
 
- #          response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: $authHeader" -d "$requestBody" $apiUrl)
+          response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: $authHeader" -d "$requestBody" $apiUrl)
 
- #          exitCode=$?
+          exitCode=$?
 
- #          if [ $exitCode -eq 0 ]; then
+          if [ $exitCode -eq 0 ]; then
 
- #          echo "API call successful!"
+          echo "API call successful!"
 
- #          echo "Response: $response"
+          echo "Response: $response"
 
- #          else
+          else
 
- #          echo "API call failed!"
+          echo "API call failed!"
 
- #          echo "Response: $response"
+          echo "Response: $response"
 
- #          exit 1
+          exit 1
 
- #          fi
+          fi
  deploy:
        name: Deploy
-        #needs: post_api_call_perf
+        needs: post_api_call_perf
        runs-on: ubuntu-latest
        steps:     
             # - name: ServiceNow DevOps Change Automation
